import type { Theme } from "./types";

export const warmHandmade: Theme = {
  id: "warm-handmade",
  name: "Warm & Handmade",
  description: "Kraft paper, wax seals, handwritten notes. Feels like a letter tucked into a drawer.",
  tokens: {
    colors: {
      background: "#f6ecd9",
      surface: "#f1e3c8",
      paper: "#eadfc1",
      ink: "#3b2a1e",
      accent: "#c06a4a",
      seal: "#a02822",
      muted: "#8b7455",
      shadow: "rgba(72, 47, 24, 0.25)",
    },
    radii: { sm: "6px", md: "12px", lg: "22px" },
    fonts: {
      display: "var(--font-display-warm)",
      body: "var(--font-body-warm)",
      hand: "var(--font-hand-warm)",
    },
    timing: { openDuration: 1.6, easing: "power3.inOut", paperRustle: 0.35 },
    texture: { paperUrl: "/textures/kraft.svg", grain: "soft" },
  },
  designs: [
    {
      id: "kraft-classic",
      themeId: "warm-handmade",
      name: "Kraft Classic",
      paper: "#d7b27a",
      flap: "#c69c62",
      seal: "#a02822",
      pattern: "none",
      description: "Brown kraft with a deep red wax seal.",
    },
    {
      id: "cream-scallop",
      themeId: "warm-handmade",
      name: "Cream Scallop",
      paper: "#f3e4c2",
      flap: "#ecd6a8",
      seal: "#b84a34",
      accent: "#b07a3a",
      pattern: "linen",
      description: "Buttery cream with a scalloped flap and linen weave.",
    },
    {
      id: "sage-botanical",
      themeId: "warm-handmade",
      name: "Sage Botanical",
      paper: "#c8ceaa",
      flap: "#b4bd93",
      seal: "#3d5c3a",
      accent: "#3d5c3a",
      pattern: "botanical",
      description: "Sage paper with pressed leaf motifs.",
    },
    {
      id: "blush-linen",
      themeId: "warm-handmade",
      name: "Blush Linen",
      paper: "#ebc7be",
      flap: "#dcb1a6",
      seal: "#7a2e2a",
      pattern: "linen",
      description: "Soft blush with a textured linen grain.",
    },
  ],
};
